config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'artists#index'

  get "myartists" => "artists#myartists"

  resources :artists do
    resources :images
  end

end

app/models/artist.rb
class Artist < ActiveRecord::Base
  belongs_to :user
  has_many :images, dependent: :destroy
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :artist
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :artists
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:create, :edit, :update, :destroy]

  def index
    @artists = Artist.all.order('name ASC')
  end

  def myartists
    @artists = current_user.artists.order('name ASC')
  end

  def new
    @artist = Artist.new
  end

  def create
    @artist = current_user.artists.create!(artist_params)
    redirect_to artist_path(@artist)
  end

  def show
  end

  def edit
  end

  def update
    @artist.update(artist_params)
    redirect_to artist_path(@artist)
  end

  def destroy
    @artist.destroy
    redirect_to artists_path
  end


  private
  def artist_params
    params.require(:artist).permit(:name, :photo_url)
  end

  def set_artist
    @artist = Artist.find(params[:id])
  end


end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_artist, only: [:new, :create, :edit, :destroy]
  before_action :set_image, only: [:show, :edit, :update, :destroy]

  def index
    @images = Image.all
  end

  def new
    @image = Image.new
  end

  def create
    @image = @artist.images.create(image_params)
    redirect_to artist_path(@artist)
  end

  def show
  end

  def edit
  end

  def update
    @image.update(image_params)
    redirect_to artist_image_path
  end

  def destroy
    @image.destroy
    redirect_to artist_path(@artist)
  end

  private
  def image_params
    params.require(:image).permit(:date, :venue, :location, :photo_url, :artist_id)
  end

  def set_image
    @image = Image.find(params[:id])
  end

  def set_artist
    @artist = Artist.find(params[:artist_id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/artists/_form.html.erb
<%= form_for(@artist) do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :photo_url, "Photo URL" %>
  <%= f.text_field :photo_url %>

  <%= f.submit %>

<% end %>

app/views/artists/edit.html.erb
<h2>Edit Artist</h2>

<%= render partial: "form" %>

<%= form_for(@artist, method: :delete) do |f| %>
  <%= f.submit "Delete Artist", class: "delete" %>
<% end  %>

app/views/artists/index.html.erb
<h2>Artists</h2>

<% @artists.each do |artist| %>
  <div class="imagegrid">

    <%= link_to (image_tag artist.photo_url, class: 'artistPhoto', alt: "Photo of #{artist.name}" ), artist_path(artist) %>
    <%= link_to artist.name, artist_path(artist), class: "nameDisplay" %>

  </div>
<% end %>

<%= link_to image_tag('newArtist.jpg', class: 'newArtist'), new_artist_path %>

app/views/artists/myartists.html.erb
<h2>My Artists</h2>

<% @artists.each do |artist| %>
  <div class="imagegrid">

    <%= link_to (image_tag artist.photo_url, class: 'artistPhoto', alt: "Photo of #{artist.name}" ), artist_path(artist) %>
    <%= link_to artist.name, artist_path(artist), class: "nameDisplay" %>

  </div>
<% end %>
<%= link_to image_tag('newArtist.jpg', class: 'newArtist'), new_artist_path %>

app/views/artists/new.html.erb
<h2>Add New Artist</h2>

<%= form_for(@artist) do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :photo_url, "Photo URL" %>
  <%= f.text_field :photo_url %>

  <%= f.submit %>

<% end %>

app/views/artists/show.html.erb
<h2><%= @artist.name %></h2>

<%= image_tag @artist.photo_url, class: "artistheader", alt: "Photo of #{@artist.name}" %>

<h3>Images</h3>

<% @artist.images.each do |image| %>
  <%= link_to image_tag(image.photo_url, class: "artistImages"), artist_image_path(@artist, image) %>
<% end %>

<%= link_to image_tag('newImage.jpg', class: 'newImage'), new_artist_image_path(@artist) %>
<h2><%= link_to "Edit/Delte Artist", edit_artist_path %></h2>

app/views/images/_form.html.erb
<%= form_for [@artist, @image] do |f| %>

  <%= f.label :date %>
  <%= f.text_field :date, :placeholder => "MM/DD/YYYY"%>

  <%= f.label :venue %>
  <%= f.text_field :venue %>

  <%= f.label :location %>
  <%= f.text_field :location %>

  <%= f.label :photo_url, "Photo URL" %>
  <%= f.text_field :photo_url %>

  <%= f.submit %>
<% end  %>

app/views/images/edit.html.erb
<h2>Edit/Delete Image</h2>

<%= render partial: "form" %>

<%= form_for [@artist, @image], method: :delete do |f| %>
  <%= f.submit "Delete Image", class: "delete" %>
<% end  %>

app/views/images/new.html.erb
<h2>New Image</h2>

<%= render partial: "form" %>

app/views/images/show.html.erb
<%= image_tag @image.photo_url, class: "indivImages "%>

<ul>
<li><%= @image.date.strftime("%B %d, %Y") %></li>
<li><%= @image.venue %></li>
<li><%= @image.location %></li>
</ul>

<h2><%= link_to "Edit/Delte Image", edit_artist_image_path %></h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Goers</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <h1>gO-ers</h1>
  <nav>
    <%= link_to "Home", root_path %>
    <% if current_user %>
      <%= link_to 'My Artists', myartists_path %>
    <% else %>
    <% end %>
  </nav>

  <div class="devise">
    <% if current_user %>
      <h3><%= link_to 'Signout', destroy_user_session_path, :method => :delete %></h3>
    <% else %>
      <h3><%= link_to 'Signup', new_user_registration_path %></h3>
      <h3><%= link_to 'Login', new_user_session_path %></h3>
    <% end %>
  </div>

<%= yield %>

</body>
</html>